<?php
/** @var array $FIELDSTITLES */
/** @var string $ROUTENAME */

echo
'<?php
/** @var $this Zend\View\Renderer\PhpRenderer */
$urlCreate = $this->url(\'admin/'.$ROUTENAME.'\', array(\'action\' => \'create\'));
?>
<h2>Records</h2>

<ul class="breadcrumb">
	<li class="pull-right"><a href="<?= $urlCreate; ?>">Add new record</a></li>
	<li></li>
</ul>

<?= $this->messagesShow(); ?>

<?php if (count($this->items)) { ?>

	<table class="table table-striped table-bordered">
	<tr>
';
foreach ($FIELDSTITLES as $title)
	echo "\t\t<th>$title</th>\n";

echo
'		<th>Options</th>
	</tr>
	<?php foreach ($this->items as $item) { ?>
		<?php
		$urlView = $this->url(\''.$ROUTENAME.'\', array(\'action\' => $item->id));
		$urlEdit = $this->url(\'admin/'.$ROUTENAME.'/query\', array(\'action\' => \'edit\', \'id\' => $item->id));
		$urlDel = $this->url(\'admin/'.$ROUTENAME.'/query\', array(\'action\' => \'remove\', \'id\' => $item->id));
		?>
		<tr>
';

foreach ($FIELDSTITLES as $field => $title)
	echo "\t\t\t<td><?= \$item->$field; ?></td>\n";

echo
'			<td>
				<a class="btn btn-mini" href="<?= $urlView; ?>" title="view"><i class="icon-search"></i></a>
				<a class="btn btn-mini" href="<?= $urlEdit; ?>" title="edit"><i class="icon-pencil"></i></a>
				<a class="btn btn-mini" href="<?= $urlDel; ?>" title="remove"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php } ?>
	</table>

<?php } else { ?>
	<p>There are no saved records</p>
<?php } ?>
';